const byId = (id) => document.getElementById(id);

export const dom = {
  loginBtn: byId("login-btn"),
  saveBtn: byId("save-btn"),
  logoutBtn: byId("logout-btn"),
  loginGuide: byId("loginGuide"),
  userEmailSpan: byId("user-email"),
  loginSection: byId("login-section"),
  loadingSection: byId("loading-section"),
  bookmarkSection: byId("bookmark-section"),
  currentUrlDiv: byId("current-url"),
  collectionDropdown: byId("collection-dropdown"),
  dropdownSelected: byId("dropdownSelected"),
  dropdownSelectedText: byId("dropdownSelectedText"),
  dropdownOptions: byId("dropdownOptions"),
  addCollectionModal: byId("addCollectionModal"),
  confirmCollectionBtn: byId("confirmCollectionBtn"),
  cancelCollectionBtn: byId("cancelCollectionBtn"),
  collectionNameInput: byId("collectionNameInput"),
  collectionIconInput: byId("collectionIconInput"),
  descriptionInput: byId("description-input"),
  tagInput: byId("tag-input"),
  tagsDisplay: byId("tags-display"),
  themeToggle: byId("themeToggle"),
  themeIcon: byId("themeIcon"),
  languageSettingsBtn: byId("languageSettings"),
  languageCancelBtn: byId("languageCancelBtn"),
  languageSaveBtn: byId("languageSaveBtn"),
  languageModal: byId("languageModal"),
  toast: byId("toast"),
};
